#!/usr/bin/env bash
# A little helper script to calculate SHA512 sums for various files in dotnet
set -euo pipefail

for version in "5.0.0" "5.0.4" ; do
    for platform in "linux" "osx" ; do
        pname="dotnet-runtime"
        url="https://dotnetcli.azureedge.net/dotnet/Runtime/${version}/${pname}-${version}-${platform}-x64.tar.gz"
        sum=$(curl -sSL "$url" | sha512sum -b)
        echo "$version $platform $pname $sum"
    done
done

for version in "5.0.100" "5.0.201" ; do
    for platform in "linux" "osx" ; do
        pname="dotnet-sdk"
        url="https://dotnetcli.azureedge.net/dotnet/Sdk/${version}/${pname}-${version}-${platform}-x64.tar.gz";
        sum=$(curl -sSL "$url" | sha512sum -b)
        echo "$version $platform $pname $sum"
    done
done

