#!/usr/bin/env bash
#
# Overrides the default command running behavior of Buildkite
# to setup the Buildkite worker's shell environment using
# direnv and NixOS. This ensures that executing build steps
# behaves identically to the developer's workstation.

set -euo pipefail

#########################
# Setup shell environment
#########################

# Set the NIX_PATH for our builder to the root user's profile. This is
# the only user with a channel we have configured on our build workers.
export NIX_PATH=nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos

# The following 4 lines are functionally equivalent to running
# `direnv allow` from an interactive shell.
PROMPT_COMMAND=""
eval "$(direnv hook bash)"
eval "$(direnv stdlib)"
source ".envrc"

#########################
# Run original command
#########################

eval "$BUILDKITE_COMMAND"
