#!/usr/bin/env bash
#
# Runs after the source code checkout and prepares the
# source tree before running the `pre-command` and
# `command` hooks.

set -euo pipefail

#########################
# Setup Git LFS
#########################

git lfs install
git lfs pull
