#!/usr/bin/env bash
#
# Runs before the build command and sets environment variables
# specific for the repository's project before running the
# `command` hook.

set -euo pipefail

export BUILD_SERVER=1
